version: '3.7'

services:
  redis:
    image: redis:alpine
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./:/usr/src/python/shore/
    ports:
      - 8888:8888
    env_file:
      - .env.docker
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A shore.celery worker -l info
    volumes:
      - ./:/usr/src/python/shore/
    env_file:
      - .env.docker
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A shore.celery beat -l info
    volumes:
      - ./:/usr/src/python/shore/
    env_file:
      - .env.docker
    depends_on:
      - redis