# Generated by Django 3.2.12 on 2022-03-01 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_adds_custom_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_phrase', models.CharField(help_text='Name of the product.', max_length=255)),
                ('frequency', models.IntegerField(choices=[(2, 'Two'), (15, 'Fifteen'), (30, 'Thirty')], help_text='Price of the product.')),
                ('is_reverse', models.BooleanField(default=True, help_text='Whether to show results in reverse order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_subscription',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
